# Generated by Django 3.0.8 on 2020-08-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
