# Generated by Django 3.0.8 on 2020-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200810_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
