# Generated by Django 3.0.8 on 2020-08-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200811_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='newsstory',
            old_name='categories',
            new_name='story_category',
        ),
    ]
