# Generated by Django 3.0.8 on 2020-08-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200812_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='story_category',
            field=models.ManyToManyField(related_name='stories', to='news.Category'),
        ),
    ]
