# Generated by Django 3.0.8 on 2020-08-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20200812_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
