# Generated by Django 3.0.8 on 2020-08-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20200812_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='mod_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
