# Generated by Django 3.0.8 on 2020-08-12 03:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_newsstory_mod_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='mod_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 3, 50, 52, 955840, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 3, 50, 52, 955799, tzinfo=utc)),
        ),
    ]
