# Generated by Django 3.0.8 on 2020-08-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
